version: "3.7"
services: 
  postgres:
    image: "postgres"
  redis:
    image: "redis"
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    image: samirprakash/multi-tier/nginx:develop
    restart: always
    ports:
      - 3050:80
    depends_on: 
      - client
      - api
      - worker
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    image: samirprakash/multi-tier/client:develop
    volumes:
      - /app/node_modules
      - ./client:/app
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    image: samirprakash/multi-tier/api:develop
    volumes:
      - /app/node_modules
      - ./api:/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGUSER=postgres
    depends_on: 
      - postgres
      - redis
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    image: samirprakash/multi-tier/worker:develop
    volumes:
      - /app/node_modules
      - ./worker:/app
    depends_on: 
      - redis