version: "3.7"
services: 
  postgres:
    image: "postgres"
  redis:
    image: "redis"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    image: samirprakash/multi-tier/client:develop
    volumes:
      - /app/node_modules
      - ./client:/app
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    image: samirprakash/multi-tier/server:develop
    volumes:
      - /app/node_modules
      - ./server:/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGUSER=postgres
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    image: samirprakash/multi-tier/worker:develop
    volumes:
      - /app/node_modules
      - ./worker:/app